// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	updatemanifest "github.com/aws/amazon-ssm-agent/agent/updateutil/updatemanifest"
)

// T is an autogenerated mock type for the T type
type T struct {
	mock.Mock
}

// DownloadManifest provides a mock function with given fields: manifest, manifestUrl
func (_m *T) DownloadManifest(manifest updatemanifest.T, manifestUrl string) error {
	ret := _m.Called(manifest, manifestUrl)

	var r0 error
	if rf, ok := ret.Get(0).(func(updatemanifest.T, string) error); ok {
		r0 = rf(manifest, manifestUrl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DownloadUpdater provides a mock function with given fields: manifest, updaterPackageName, downloadPath
func (_m *T) DownloadUpdater(manifest updatemanifest.T, updaterPackageName string, downloadPath string) (string, error) {
	ret := _m.Called(manifest, updaterPackageName, downloadPath)

	var r0 string
	if rf, ok := ret.Get(0).(func(updatemanifest.T, string, string) string); ok {
		r0 = rf(manifest, updaterPackageName, downloadPath)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(updatemanifest.T, string, string) error); ok {
		r1 = rf(manifest, updaterPackageName, downloadPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
