// Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may not
// use this file except in compliance with the License. A copy of the
// License is located at
//
// http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
// either express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	updatemanifest "github.com/aws/amazon-ssm-agent/agent/updateutil/updatemanifest"
	updates3util "github.com/aws/amazon-ssm-agent/agent/updateutil/updates3util"
	mock "github.com/stretchr/testify/mock"
)

// T is an autogenerated mock type for the T type
type T struct {
	mock.Mock
}

// DownloadManifest provides a mock function with given fields: manifest, manifestUrl
func (_m *T) DownloadManifest(manifest updatemanifest.T, manifestUrl string) *updates3util.UpdateErrorStruct {
	ret := _m.Called(manifest, manifestUrl)

	var r0 *updates3util.UpdateErrorStruct
	if rf, ok := ret.Get(0).(func(updatemanifest.T, string) *updates3util.UpdateErrorStruct); ok {
		r0 = rf(manifest, manifestUrl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*updates3util.UpdateErrorStruct)
		}
	}

	return r0
}

// DownloadUpdater provides a mock function with given fields: manifest, updaterPackageName, downloadPath
func (_m *T) DownloadUpdater(manifest updatemanifest.T, updaterPackageName string, downloadPath string) (string, error) {
	ret := _m.Called(manifest, updaterPackageName, downloadPath)

	var r0 string
	if rf, ok := ret.Get(0).(func(updatemanifest.T, string, string) string); ok {
		r0 = rf(manifest, updaterPackageName, downloadPath)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(updatemanifest.T, string, string) error); ok {
		r1 = rf(manifest, updaterPackageName, downloadPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
