// Code generated by mockery v2.23.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IClient is an autogenerated mock type for the IClient type
type IClient struct {
	mock.Mock
}

// RegisterManagedInstanceWithContext provides a mock function with given fields: ctx, publicKey, publicKeyType, fingerprint, iamRole, tagsJson
func (_m *IClient) RegisterManagedInstanceWithContext(ctx context.Context, publicKey string, publicKeyType string, fingerprint string, iamRole string, tagsJson string) (string, error) {
	ret := _m.Called(ctx, publicKey, publicKeyType, fingerprint, iamRole, tagsJson)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (string, error)); ok {
		return rf(ctx, publicKey, publicKeyType, fingerprint, iamRole, tagsJson)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) string); ok {
		r0 = rf(ctx, publicKey, publicKeyType, fingerprint, iamRole, tagsJson)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = rf(ctx, publicKey, publicKeyType, fingerprint, iamRole, tagsJson)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewIClient creates a new instance of IClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIClient(t mockConstructorTestingTNewIClient) *IClient {
	mock := &IClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
