// Code generated by mockery v2.23.2. DO NOT EDIT.

package mocks

import (
	context "context"

	request "github.com/aws/aws-sdk-go/aws/request"
	mock "github.com/stretchr/testify/mock"

	ssm "github.com/aws/aws-sdk-go/service/ssm"
)

// ISsmSdk is an autogenerated mock type for the ISsmSdk type
type ISsmSdk struct {
	mock.Mock
}

// RegisterManagedInstanceWithContext provides a mock function with given fields: ctx, input, opts
func (_m *ISsmSdk) RegisterManagedInstanceWithContext(ctx context.Context, input *ssm.RegisterManagedInstanceInput, opts ...request.Option) (*ssm.RegisterManagedInstanceOutput, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, input)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ssm.RegisterManagedInstanceOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssm.RegisterManagedInstanceInput, ...request.Option) (*ssm.RegisterManagedInstanceOutput, error)); ok {
		return rf(ctx, input, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssm.RegisterManagedInstanceInput, ...request.Option) *ssm.RegisterManagedInstanceOutput); ok {
		r0 = rf(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.RegisterManagedInstanceOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssm.RegisterManagedInstanceInput, ...request.Option) error); ok {
		r1 = rf(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewISsmSdk interface {
	mock.TestingT
	Cleanup(func())
}

// NewISsmSdk creates a new instance of ISsmSdk. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewISsmSdk(t mockConstructorTestingTNewISsmSdk) *ISsmSdk {
	mock := &ISsmSdk{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
