// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "github.com/aws/amazon-ssm-agent/core/workerprovider/longrunningprovider/model"
	mock "github.com/stretchr/testify/mock"
)

// IDiscover is an autogenerated mock type for the IDiscover type
type IDiscover struct {
	mock.Mock
}

// FindWorkerConfigs provides a mock function with given fields:
func (_m *IDiscover) FindWorkerConfigs() map[string]*model.WorkerConfig {
	ret := _m.Called()

	var r0 map[string]*model.WorkerConfig
	if rf, ok := ret.Get(0).(func() map[string]*model.WorkerConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*model.WorkerConfig)
		}
	}

	return r0
}
