// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// IEC2MdsSdkClient is an autogenerated mock type for the IEC2MdsSdkClient type
type IEC2MdsSdkClient struct {
	mock.Mock
}

// GetMetadata provides a mock function with given fields: _a0
func (_m *IEC2MdsSdkClient) GetMetadata(_a0 string) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Region provides a mock function with given fields:
func (_m *IEC2MdsSdkClient) Region() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIEC2MdsSdkClient creates a new instance of IEC2MdsSdkClient. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIEC2MdsSdkClient(t testing.TB) *IEC2MdsSdkClient {
	mock := &IEC2MdsSdkClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
