// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	message "github.com/aws/amazon-ssm-agent/common/message"
	mock "github.com/stretchr/testify/mock"

	model "github.com/aws/amazon-ssm-agent/core/workerprovider/longrunningprovider/model"
)

// IProvider is an autogenerated mock type for the IProvider type
type IProvider struct {
	mock.Mock
}

// Monitor provides a mock function with given fields: _a0, _a1
func (_m *IProvider) Monitor(_a0 map[string]*model.WorkerConfig, _a1 []*message.Message) {
	_m.Called(_a0, _a1)
}

// Start provides a mock function with given fields: _a0, _a1
func (_m *IProvider) Start(_a0 map[string]*model.WorkerConfig, _a1 []*message.Message) {
	_m.Called(_a0, _a1)
}

// KillAllWorkerProcesses provides a mock function
func (_m *IProvider) KillAllWorkerProcesses() {
	_m.Called()
}
