// Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may not
// use this file except in compliance with the License. A copy of the
// License is located at
//
// http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
// either express or implied. See the License for the specific language governing
// permissions and limitations under the License.
// Code generated by mockery v1.0.0
package rebooter

import (
	log "github.com/aws/amazon-ssm-agent/agent/log"
	"github.com/aws/amazon-ssm-agent/agent/rebooter"
	mock "github.com/stretchr/testify/mock"
)

// MockIRebootType is an autogenerated mock type for the IRebootType type
type IRebootType struct {
	mock.Mock
}

// GetChannel provides a mock function with given fields:
func (_m *IRebootType) GetChannel() chan rebooter.RebootType {
	ret := _m.Called()

	var r0 chan rebooter.RebootType
	if rf, ok := ret.Get(0).(func() chan rebooter.RebootType); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan rebooter.RebootType)
		}
	}

	return r0
}

// RebootMachine provides a mock function with given fields: _a0
func (_m *IRebootType) RebootMachine(_a0 log.T) {
	_m.Called(_a0)
}
