// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import (
	contracts "github.com/aws/amazon-ssm-agent/agent/session/contracts"
	datachannel "github.com/aws/amazon-ssm-agent/agent/session/datachannel"

	log "github.com/aws/amazon-ssm-agent/agent/log"

	mock "github.com/stretchr/testify/mock"
)

// IPortSession is an autogenerated mock type for the IPortSession type
type IPortSession struct {
	mock.Mock
}

// HandleStreamMessage provides a mock function with given fields: _a0, streamDataMessage
func (_m *IPortSession) HandleStreamMessage(_a0 log.T, streamDataMessage contracts.AgentMessage) error {
	ret := _m.Called(_a0, streamDataMessage)

	var r0 error
	if rf, ok := ret.Get(0).(func(log.T, contracts.AgentMessage) error); ok {
		r0 = rf(_a0, streamDataMessage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InitializeSession provides a mock function with given fields: _a0, serverPort
func (_m *IPortSession) InitializeSession(_a0 log.T) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(log.T) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *IPortSession) Stop() {
	_m.Called()
}

// WritePump provides a mock function with given fields: _a0, channel
func (_m *IPortSession) WritePump(_a0 log.T, channel datachannel.IDataChannel) int {
	ret := _m.Called(_a0, channel)

	var r0 int
	if rf, ok := ret.Get(0).(func(log.T, datachannel.IDataChannel) int); ok {
		r0 = rf(_a0, channel)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
