// Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may not
// use this file except in compliance with the License. A copy of the
// License is located at
//
// http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
// either express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// IKMSService is an autogenerated mock type for the IKMSService type
type IKMSService struct {
	mock.Mock
}

// GenerateDataKey provides a mock function with given fields: kmsKeyId, context
func (_m *IKMSService) GenerateDataKey(kmsKeyId string, context map[string]*string) ([]byte, []byte, error) {
	ret := _m.Called(kmsKeyId, context)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, map[string]*string) []byte); ok {
		r0 = rf(kmsKeyId, context)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 []byte
	if rf, ok := ret.Get(1).(func(string, map[string]*string) []byte); ok {
		r1 = rf(kmsKeyId, context)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, map[string]*string) error); ok {
		r2 = rf(kmsKeyId, context)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
