// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IStore is an autogenerated mock type for the IStore type
type IStore struct {
	mock.Mock
}

// Read provides a mock function with given fields: name, dest
func (_m *IStore) Read(name string, dest interface{}) error {
	ret := _m.Called(name, dest)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(name, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Write provides a mock function with given fields: datajson, path, name
func (_m *IStore) Write(datajson string, path string, name string) error {
	ret := _m.Called(datajson, path, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(datajson, path, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
