// Copyright 2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Amazon Software License (the "License"). You may not
// use this file except in compliance with the License. A copy of the
// License is located at
//
// http://aws.amazon.com/asl/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// This is an autogenerated file and should not be edited.
// Please DO NOT commit any changes to this file.

// Package version contains constants to indicate the current version of the
// agent. It is autogenerated.
package version

// Version is the version of the Agent
const Version = "1.2.0.0"
