// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	ec2roleprovider "github.com/aws/amazon-ssm-agent/common/identity/credentialproviders/ec2roleprovider"
	credentials "github.com/aws/aws-sdk-go/aws/credentials"
	mock "github.com/stretchr/testify/mock"

	testing "testing"

	time "time"
)

// IEC2RoleProvider is an autogenerated mock type for the IEC2RoleProvider type
type IEC2RoleProvider struct {
	mock.Mock
}

// ExpiresAt provides a mock function with given fields:
func (_m *IEC2RoleProvider) ExpiresAt() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// GetInnerProvider provides a mock function with given fields:
func (_m *IEC2RoleProvider) GetInnerProvider() ec2roleprovider.IInnerProvider {
	ret := _m.Called()

	var r0 ec2roleprovider.IInnerProvider
	if rf, ok := ret.Get(0).(func() ec2roleprovider.IInnerProvider); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ec2roleprovider.IInnerProvider)
		}
	}

	return r0
}

// IsExpired provides a mock function with given fields:
func (_m *IEC2RoleProvider) IsExpired() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Retrieve provides a mock function with given fields:
func (_m *IEC2RoleProvider) Retrieve() (credentials.Value, error) {
	ret := _m.Called()

	var r0 credentials.Value
	if rf, ok := ret.Get(0).(func() credentials.Value); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(credentials.Value)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShareFile provides a mock function with given fields:
func (_m *IEC2RoleProvider) ShareFile() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ShareProfile provides a mock function with given fields:
func (_m *IEC2RoleProvider) ShareProfile() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SharesCredentials provides a mock function with given fields:
func (_m *IEC2RoleProvider) SharesCredentials() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewIEC2RoleProvider creates a new instance of IEC2RoleProvider. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIEC2RoleProvider(t testing.TB) *IEC2RoleProvider {
	mock := &IEC2RoleProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
