// Code generated by mockery v2.23.2. DO NOT EDIT.

package mocks

import (
	context "context"

	credentials "github.com/aws/aws-sdk-go/aws/credentials"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// IInnerProvider is an autogenerated mock type for the IInnerProvider type
type IInnerProvider struct {
	mock.Mock
}

// ExpiresAt provides a mock function with given fields:
func (_m *IInnerProvider) ExpiresAt() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// IsExpired provides a mock function with given fields:
func (_m *IInnerProvider) IsExpired() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Retrieve provides a mock function with given fields:
func (_m *IInnerProvider) Retrieve() (credentials.Value, error) {
	ret := _m.Called()

	var r0 credentials.Value
	var r1 error
	if rf, ok := ret.Get(0).(func() (credentials.Value, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() credentials.Value); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(credentials.Value)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveWithContext provides a mock function with given fields: ctx
func (_m *IInnerProvider) RetrieveWithContext(ctx context.Context) (credentials.Value, error) {
	ret := _m.Called(ctx)

	var r0 credentials.Value
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (credentials.Value, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) credentials.Value); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(credentials.Value)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetExpiration provides a mock function with given fields: expiration, window
func (_m *IInnerProvider) SetExpiration(expiration time.Time, window time.Duration) {
	_m.Called(expiration, window)
}

type mockConstructorTestingTNewIInnerProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewIInnerProvider creates a new instance of IInnerProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIInnerProvider(t mockConstructorTestingTNewIInnerProvider) *IInnerProvider {
	mock := &IInnerProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
