// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	credentials "github.com/aws/aws-sdk-go/aws/credentials"

	mock "github.com/stretchr/testify/mock"

	testing "testing"

	time "time"
)

// IInnerProvider is an autogenerated mock type for the IInnerProvider type
type IInnerProvider struct {
	mock.Mock
}

// ExpiresAt provides a mock function with given fields:
func (_m *IInnerProvider) ExpiresAt() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// IsExpired provides a mock function with given fields:
func (_m *IInnerProvider) IsExpired() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Retrieve provides a mock function with given fields:
func (_m *IInnerProvider) Retrieve() (credentials.Value, error) {
	ret := _m.Called()

	var r0 credentials.Value
	if rf, ok := ret.Get(0).(func() credentials.Value); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(credentials.Value)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIInnerProvider creates a new instance of IInnerProvider. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIInnerProvider(t testing.TB) *IInnerProvider {
	mock := &IInnerProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
