// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IEndpointHelper is an autogenerated mock type for the IEndpointHelper type
type IEndpointHelper struct {
	mock.Mock
}

// GetServiceEndpoint provides a mock function with given fields: service, region
func (_m *IEndpointHelper) GetServiceEndpoint(service string, region string) string {
	ret := _m.Called(service, region)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(service, region)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
