// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	identity "github.com/aws/amazon-ssm-agent/common/identity"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// IInnerIdentityGetter is an autogenerated mock type for the IInnerIdentityGetter type
type IInnerIdentityGetter struct {
	mock.Mock
}

// GetInner provides a mock function with given fields:
func (_m *IInnerIdentityGetter) GetInner() identity.IAgentIdentityInner {
	ret := _m.Called()

	var r0 identity.IAgentIdentityInner
	if rf, ok := ret.Get(0).(func() identity.IAgentIdentityInner); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(identity.IAgentIdentityInner)
		}
	}

	return r0
}

// NewIInnerIdentityGetter creates a new instance of IInnerIdentityGetter. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIInnerIdentityGetter(t testing.TB) *IInnerIdentityGetter {
	mock := &IInnerIdentityGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
