// Code generated by mockery v2.10.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IMetadataIdentity is an autogenerated mock type for the IMetadataIdentity type
type IMetadataIdentity struct {
	mock.Mock
}

// VpcPrimaryCIDRBlock provides a mock function with given fields:
func (_m *IMetadataIdentity) VpcPrimaryCIDRBlock() (map[string][]string, error) {
	ret := _m.Called()

	var r0 map[string][]string
	if rf, ok := ret.Get(0).(func() map[string][]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
