// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	ssm "github.com/aws/aws-sdk-go/service/ssm"
)

// ISSMClient is an autogenerated mock type for the ISSMClient type
type ISSMClient struct {
	mock.Mock
}

// RequestManagedInstanceRoleToken provides a mock function with given fields: input
func (_m *ISSMClient) RequestManagedInstanceRoleToken(input *ssm.RequestManagedInstanceRoleTokenInput) (*ssm.RequestManagedInstanceRoleTokenOutput, error) {
	ret := _m.Called(input)

	var r0 *ssm.RequestManagedInstanceRoleTokenOutput
	if rf, ok := ret.Get(0).(func(*ssm.RequestManagedInstanceRoleTokenInput) *ssm.RequestManagedInstanceRoleTokenOutput); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.RequestManagedInstanceRoleTokenOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*ssm.RequestManagedInstanceRoleTokenInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateInstanceInformation provides a mock function with given fields: input
func (_m *ISSMClient) UpdateInstanceInformation(input *ssm.UpdateInstanceInformationInput) (*ssm.UpdateInstanceInformationOutput, error) {
	ret := _m.Called(input)

	var r0 *ssm.UpdateInstanceInformationOutput
	if rf, ok := ret.Get(0).(func(*ssm.UpdateInstanceInformationInput) *ssm.UpdateInstanceInformationOutput); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.UpdateInstanceInformationOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*ssm.UpdateInstanceInformationInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
