// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// ICoreModuleWrapper is an autogenerated mock type for the ICoreModuleWrapper type
type ICoreModuleWrapper struct {
	mock.Mock
}

// ModuleExecute provides a mock function with given fields:
func (_m *ICoreModuleWrapper) ModuleExecute() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ModuleName provides a mock function with given fields:
func (_m *ICoreModuleWrapper) ModuleName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ModuleStop provides a mock function with given fields: waitTime
func (_m *ICoreModuleWrapper) ModuleStop(waitTime time.Duration) error {
	ret := _m.Called(waitTime)

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Duration) error); ok {
		r0 = rf(waitTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
