// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ICoreModule is an autogenerated mock type for the ICoreModule type
type ICoreModule struct {
	mock.Mock
}

// ModuleExecute provides a mock function with given fields:
func (_m *ICoreModule) ModuleExecute() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ModuleName provides a mock function with given fields:
func (_m *ICoreModule) ModuleName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ModuleStop provides a mock function with given fields:
func (_m *ICoreModule) ModuleStop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
