// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	runtimeconfig "github.com/aws/amazon-ssm-agent/common/runtimeconfig"
	mock "github.com/stretchr/testify/mock"
)

// IIdentityRuntimeConfigClient is an autogenerated mock type for the IIdentityRuntimeConfigClient type
type IIdentityRuntimeConfigClient struct {
	mock.Mock
}

// ConfigExists provides a mock function with given fields:
func (_m *IIdentityRuntimeConfigClient) ConfigExists() (bool, error) {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConfig provides a mock function with given fields:
func (_m *IIdentityRuntimeConfigClient) GetConfig() (runtimeconfig.IdentityRuntimeConfig, error) {
	ret := _m.Called()

	var r0 runtimeconfig.IdentityRuntimeConfig
	if rf, ok := ret.Get(0).(func() runtimeconfig.IdentityRuntimeConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(runtimeconfig.IdentityRuntimeConfig)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveConfig provides a mock function with given fields: _a0
func (_m *IIdentityRuntimeConfigClient) SaveConfig(_a0 runtimeconfig.IdentityRuntimeConfig) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(runtimeconfig.IdentityRuntimeConfig) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
