// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DetectorHelper is an autogenerated mock type for the DetectorHelper type
type DetectorHelper struct {
	mock.Mock
}

// GetSystemInfo provides a mock function with given fields: _a0
func (_m *DetectorHelper) GetSystemInfo(_a0 string) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MatchUuid provides a mock function with given fields: _a0
func (_m *DetectorHelper) MatchUuid(_a0 string) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
