// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// T is an autogenerated mock type for the T type
type T struct {
	mock.Mock
}

// CheckPrecondition provides a mock function with given fields: version
func (_m *T) CheckPrecondition(version string) error {
	ret := _m.Called(version)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPreconditionName provides a mock function with given fields:
func (_m *T) GetPreconditionName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
