// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	credentials "github.com/aws/aws-sdk-go/aws/credentials"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// IRemoteProvider is an autogenerated mock type for the IRemoteProvider type
type IRemoteProvider struct {
	mock.Mock
}

// IsExpired provides a mock function with given fields:
func (_m *IRemoteProvider) IsExpired() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Retrieve provides a mock function with given fields:
func (_m *IRemoteProvider) Retrieve() (credentials.Value, error) {
	ret := _m.Called()

	var r0 credentials.Value
	if rf, ok := ret.Get(0).(func() credentials.Value); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(credentials.Value)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShareFile provides a mock function with given fields:
func (_m *IRemoteProvider) ShareFile() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ShareProfile provides a mock function with given fields:
func (_m *IRemoteProvider) ShareProfile() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SharesCredentials provides a mock function with given fields:
func (_m *IRemoteProvider) SharesCredentials() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewIRemoteProvider creates a new instance of IRemoteProvider. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIRemoteProvider(t testing.TB) *IRemoteProvider {
	mock := &IRemoteProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
