// Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may not
// use this file except in compliance with the License. A copy of the
// License is located at
//
// http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
// either express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// ICoreManager is an autogenerated mock type for the ICoreManager type
type ICoreManager struct {
	mock.Mock
}

// Start provides a mock function with given fields:
func (_m *ICoreManager) Start() {
	_m.Called()
}

// Stop provides a mock function with given fields:
func (_m *ICoreManager) Stop() {
	_m.Called()
}
