// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "github.com/aws/amazon-ssm-agent/core/app/reboot/model"
	mock "github.com/stretchr/testify/mock"
)

// IContainer is an autogenerated mock type for the IContainer type
type IContainer struct {
	mock.Mock
}

// Monitor provides a mock function with given fields:
func (_m *IContainer) Monitor() {
	_m.Called()
}

// Start provides a mock function with given fields:
func (_m *IContainer) Start() {
	_m.Called()
}

// Stop provides a mock function with given fields: _a0
func (_m *IContainer) Stop(_a0 model.StopType) {
	_m.Called(_a0)
}
