// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IAuditLogTelemetry is an autogenerated mock type for the IAuditLogTelemetry type
type IAuditLogTelemetry struct {
	mock.Mock
}

// ScheduleAuditEvents provides a mock function with given fields:
func (_m *IAuditLogTelemetry) ScheduleAuditEvents() {
	_m.Called()
}

// SendAuditMessage provides a mock function with given fields:
func (_m *IAuditLogTelemetry) SendAuditMessage() {
	_m.Called()
}

// StopScheduler provides a mock function with given fields:
func (_m *IAuditLogTelemetry) StopScheduler() {
	_m.Called()
}
