// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// IExecCmd is an autogenerated mock type for the IExecCmd type
type IExecCmd struct {
	mock.Mock
}

// Pid provides a mock function with given fields:
func (_m *IExecCmd) Pid() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Kill provides a mock function with given fields:
func (_m *IExecCmd) Kill() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Start provides a mock function with given fields:
func (_m *IExecCmd) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Wait provides a mock function with given fields:
func (_m *IExecCmd) Wait() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Wait provides a mock function with given fields:
func (_m *IExecCmd) Signal(sig os.Signal) error {
	ret := _m.Called(sig)

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
