// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	log "github.com/aws/amazon-ssm-agent/agent/log"
	mock "github.com/stretchr/testify/mock"
)

// IVerificationManager is an autogenerated mock type for the IVerificationManager type
type IVerificationManager struct {
	mock.Mock
}

// VerifySignature provides a mock function with given fields: _a0, signaturePath, binaryPath, artifactsPath
func (_m *IVerificationManager) VerifySignature(_a0 log.T, signaturePath string, binaryPath string, artifactsPath string) error {
	ret := _m.Called(_a0, signaturePath, binaryPath, artifactsPath)

	var r0 error
	if rf, ok := ret.Get(0).(func(log.T, string, string, string) error); ok {
		r0 = rf(_a0, signaturePath, binaryPath, artifactsPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
