#!/bin/sh

if [ $3 == "/" ]; then
    echo "Starting agent"
    launchctl load -w /Library/LaunchDaemons/com.amazon.aws.ssm.plist
    launchctl start com.amazon.aws.ssm
else
    echo "Skipping launchctl for non-root installation"
fi
