// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	message "github.com/aws/amazon-ssm-agent/common/message"

	mock "github.com/stretchr/testify/mock"
)

// IMessageBus is an autogenerated mock type for the IMessageBus type
type IMessageBus struct {
	mock.Mock
}

// SendSurveyMessage provides a mock function with given fields: survey
func (_m *IMessageBus) SendSurveyMessage(survey *message.Message) ([]*message.Message, error) {
	ret := _m.Called(survey)

	var r0 []*message.Message
	if rf, ok := ret.Get(0).(func(*message.Message) []*message.Message); ok {
		r0 = rf(survey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*message.Message)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*message.Message) error); ok {
		r1 = rf(survey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Start provides a mock function with given fields:
func (_m *IMessageBus) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *IMessageBus) Stop() {
	_m.Called()
}
