// Code generated by mockery v2.23.2. DO NOT EDIT.

package mocks

import (
	context "context"

	request "github.com/aws/aws-sdk-go/aws/request"
	mock "github.com/stretchr/testify/mock"

	ssm "github.com/aws/aws-sdk-go/service/ssm"
)

// ISsmSdk is an autogenerated mock type for the ISsmSdk type
type ISsmSdk struct {
	mock.Mock
}

// RequestManagedInstanceRoleToken provides a mock function with given fields: input
func (_m *ISsmSdk) RequestManagedInstanceRoleToken(input *ssm.RequestManagedInstanceRoleTokenInput) (*ssm.RequestManagedInstanceRoleTokenOutput, error) {
	ret := _m.Called(input)

	var r0 *ssm.RequestManagedInstanceRoleTokenOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(*ssm.RequestManagedInstanceRoleTokenInput) (*ssm.RequestManagedInstanceRoleTokenOutput, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(*ssm.RequestManagedInstanceRoleTokenInput) *ssm.RequestManagedInstanceRoleTokenOutput); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.RequestManagedInstanceRoleTokenOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(*ssm.RequestManagedInstanceRoleTokenInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestManagedInstanceRoleTokenWithContext provides a mock function with given fields: ctx, input, opts
func (_m *ISsmSdk) RequestManagedInstanceRoleTokenWithContext(ctx context.Context, input *ssm.RequestManagedInstanceRoleTokenInput, opts ...request.Option) (*ssm.RequestManagedInstanceRoleTokenOutput, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, input)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ssm.RequestManagedInstanceRoleTokenOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssm.RequestManagedInstanceRoleTokenInput, ...request.Option) (*ssm.RequestManagedInstanceRoleTokenOutput, error)); ok {
		return rf(ctx, input, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssm.RequestManagedInstanceRoleTokenInput, ...request.Option) *ssm.RequestManagedInstanceRoleTokenOutput); ok {
		r0 = rf(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.RequestManagedInstanceRoleTokenOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssm.RequestManagedInstanceRoleTokenInput, ...request.Option) error); ok {
		r1 = rf(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateManagedInstancePublicKey provides a mock function with given fields: input
func (_m *ISsmSdk) UpdateManagedInstancePublicKey(input *ssm.UpdateManagedInstancePublicKeyInput) (*ssm.UpdateManagedInstancePublicKeyOutput, error) {
	ret := _m.Called(input)

	var r0 *ssm.UpdateManagedInstancePublicKeyOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(*ssm.UpdateManagedInstancePublicKeyInput) (*ssm.UpdateManagedInstancePublicKeyOutput, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(*ssm.UpdateManagedInstancePublicKeyInput) *ssm.UpdateManagedInstancePublicKeyOutput); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.UpdateManagedInstancePublicKeyOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(*ssm.UpdateManagedInstancePublicKeyInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateManagedInstancePublicKeyWithContext provides a mock function with given fields: ctx, input, opts
func (_m *ISsmSdk) UpdateManagedInstancePublicKeyWithContext(ctx context.Context, input *ssm.UpdateManagedInstancePublicKeyInput, opts ...request.Option) (*ssm.UpdateManagedInstancePublicKeyOutput, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, input)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ssm.UpdateManagedInstancePublicKeyOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssm.UpdateManagedInstancePublicKeyInput, ...request.Option) (*ssm.UpdateManagedInstancePublicKeyOutput, error)); ok {
		return rf(ctx, input, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssm.UpdateManagedInstancePublicKeyInput, ...request.Option) *ssm.UpdateManagedInstancePublicKeyOutput); ok {
		r0 = rf(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.UpdateManagedInstancePublicKeyOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssm.UpdateManagedInstancePublicKeyInput, ...request.Option) error); ok {
		r1 = rf(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewISsmSdk interface {
	mock.TestingT
	Cleanup(func())
}

// NewISsmSdk creates a new instance of ISsmSdk. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewISsmSdk(t mockConstructorTestingTNewISsmSdk) *ISsmSdk {
	mock := &ISsmSdk{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
