// Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may not
// use this file except in compliance with the License. A copy of the
// License is located at
//
// http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
// either express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by mockery v2.9.4. DO NOT EDIT.
package mocks

import (
	context "github.com/aws/amazon-ssm-agent/agent/context"
	health "github.com/aws/amazon-ssm-agent/agent/health"
	mock "github.com/stretchr/testify/mock"
)

// IHibernate is an autogenerated mock type for the IHibernate type
type IHibernate struct {
	mock.Mock
}

// ExecuteHibernation provides a mock function with given fields: _a0
func (_m *IHibernate) ExecuteHibernation(_a0 context.T) health.AgentState {
	ret := _m.Called(_a0)

	var r0 health.AgentState
	if rf, ok := ret.Get(0).(func(context.T) health.AgentState); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(health.AgentState)
	}

	return r0
}
